"""quote canonical price and source message

Revision ID: 135bc9f23245
Revises: c24bc9f4e3bd
Create Date: 2026-09-27 23:13:04.120015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135bc9f23245'
down_revision: Union[str, Sequence[str], None] = 'c24bc9f4e3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('price_per_canonical_paise', sa.BigInteger(), nullable=True))
    op.add_column('quotes', sa.Column('source_message_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint('quotes_source_message_id_key', 'quotes', ['source_message_id'])
    op.create_foreign_key('quotes_source_message_id_fkey', 'quotes', 'messages', ['source_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quotes_source_message_id_fkey', 'quotes', type_='foreignkey')
    op.drop_constraint('quotes_source_message_id_key', 'quotes', type_='unique')
    op.drop_column('quotes', 'source_message_id')
    op.drop_column('quotes', 'price_per_canonical_paise')
    # ### end Alembic commands ###
