"""delivery and invoice refs

Revision ID: 84fd18c451f6
Revises: 135bc9f23245
Create Date: 2026-09-28 02:55:13.165201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84fd18c451f6'
down_revision: Union[str, Sequence[str], None] = '135bc9f23245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('client_ref', sa.Text(), nullable=True))
    op.create_unique_constraint('deliveries_client_ref_key', 'deliveries', ['client_ref'])
    op.add_column('invoices', sa.Column('client_ref', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('accepted_by', sa.Uuid(), nullable=True))
    op.add_column('invoices', sa.Column('accept_note', sa.Text(), nullable=True))
    op.create_unique_constraint('invoices_client_ref_key', 'invoices', ['client_ref'])
    op.create_foreign_key('invoices_accepted_by_fkey', 'invoices', 'users', ['accepted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_accepted_by_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_client_ref_key', 'invoices', type_='unique')
    op.drop_column('invoices', 'accept_note')
    op.drop_column('invoices', 'accepted_by')
    op.drop_column('invoices', 'client_ref')
    op.drop_constraint('deliveries_client_ref_key', 'deliveries', type_='unique')
    op.drop_column('deliveries', 'client_ref')
    # ### end Alembic commands ###
