"""job seq

Revision ID: c24bc9f4e3bd
Revises: 4cc84956a6a6
Create Date: 2026-09-27 22:43:28.928346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24bc9f4e3bd'
down_revision: Union[str, Sequence[str], None] = '4cc84956a6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_unique_constraint('jobs_seq_key', 'jobs', ['seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('jobs_seq_key', 'jobs', type_='unique')
    op.drop_column('jobs', 'seq')
    # ### end Alembic commands ###
