"""bom client ref and line spec

Revision ID: cc9aa76f9d12
Revises: be5e15773afa
Create Date: 2026-09-27 22:08:21.084201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9aa76f9d12'
down_revision: Union[str, Sequence[str], None] = 'be5e15773afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_lines', sa.Column('spec', sa.Text(), nullable=True))
    op.add_column('bom_lines', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('boms', sa.Column('client_ref', sa.Text(), nullable=True))
    op.create_unique_constraint('boms_client_ref_key', 'boms', ['client_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('boms_client_ref_key', 'boms', type_='unique')
    op.drop_column('boms', 'client_ref')
    op.drop_column('bom_lines', 'notes')
    op.drop_column('bom_lines', 'spec')
    # ### end Alembic commands ###
