"""initial schema

Revision ID: dabc0594372d
Revises: 
Create Date: 2026-09-28 00:09:33.648045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dabc0594372d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Public-ID counters. Never max()+1.
SEQUENCES = ("bom_code_seq", "quote_code_seq", "neg_code_seq", "po_code_seq")

AUDIT_GUARD = """
CREATE FUNCTION audit_log_immutable() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only (% blocked)', TG_OP;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER audit_log_no_update_delete
BEFORE UPDATE OR DELETE ON audit_log
FOR EACH ROW EXECUTE FUNCTION audit_log_immutable();
"""


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    for seq in SEQUENCES:
        op.execute(f"CREATE SEQUENCE {seq}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builder_orgs',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('gstin', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin'),
    sa.UniqueConstraint('name')
    )
    op.create_table('catalog_items',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('canonical_unit', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('hsn', sa.Text(), nullable=True),
    sa.Column('default_gst_bp', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_catalog_items_category'), 'catalog_items', ['category'], unique=False)
    op.create_index('ix_catalog_items_name_trgm', 'catalog_items', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('demo_clock',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('offset_seconds', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ordering_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_jobs_status_run_at', 'jobs', ['status', 'run_at'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.create_table('vendors',
    sa.Column('legal_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('gstin', sa.Text(), nullable=True),
    sa.Column('opted_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('item_codes', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('brands', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('service_pincodes', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('service_radius_km', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('capacity_per_week', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_order_qty', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('on_time_bp', sa.Integer(), nullable=False),
    sa.Column('qty_accuracy_bp', sa.Integer(), nullable=False),
    sa.Column('invoice_match_bp', sa.Integer(), nullable=False),
    sa.Column('response_bp', sa.Integer(), nullable=False),
    sa.Column('quality_bp', sa.Integer(), nullable=False),
    sa.Column('orders_completed', sa.Integer(), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gstin'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('audit_log',
    sa.Column('builder_org_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_builder_org_id'), 'audit_log', ['builder_org_id'], unique=False)
    op.create_table('builder_vendor_links',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('builder_org_id', 'vendor_id')
    )
    op.create_index(op.f('ix_builder_vendor_links_builder_org_id'), 'builder_vendor_links', ['builder_org_id'], unique=False)
    op.create_index(op.f('ix_builder_vendor_links_vendor_id'), 'builder_vendor_links', ['vendor_id'], unique=False)
    op.create_table('sites',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('area', sa.Text(), nullable=False),
    sa.Column('pincode', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('builder_org_id', 'name')
    )
    op.create_index(op.f('ix_sites_builder_org_id'), 'sites', ['builder_org_id'], unique=False)
    op.create_table('unit_conversions',
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('from_unit', sa.Text(), nullable=False),
    sa.Column('to_unit', sa.Text(), nullable=False),
    sa.Column('numerator', sa.BigInteger(), nullable=False),
    sa.Column('denominator', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'from_unit', 'to_unit', postgresql_nulls_not_distinct=True)
    )
    op.create_table('users',
    sa.Column('builder_org_id', sa.Uuid(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('approval_limit_paise', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_builder_org_id'), 'users', ['builder_org_id'], unique=False)
    op.create_table('boms',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('public_code', sa.Text(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('original_file_ref', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_code')
    )
    op.create_index(op.f('ix_boms_builder_org_id'), 'boms', ['builder_org_id'], unique=False)
    op.create_table('bom_lines',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('bom_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('qty_canonical_milli', sa.BigInteger(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('qty_entered', sa.Text(), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=False),
    sa.Column('partial_allowed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_id', 'line_no')
    )
    op.create_index(op.f('ix_bom_lines_bom_id'), 'bom_lines', ['bom_id'], unique=False)
    op.create_index(op.f('ix_bom_lines_builder_org_id'), 'bom_lines', ['builder_org_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('bom_line_id', sa.Uuid(), nullable=False),
    sa.Column('public_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('bid_window_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bid_window_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_extended', sa.Boolean(), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('shortlist_size', sa.Integer(), nullable=False),
    sa.Column('target_price_paise', sa.BigInteger(), nullable=True),
    sa.Column('max_price_paise', sa.BigInteger(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bom_line_id'], ['bom_lines.id'], ),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_code')
    )
    op.create_index(op.f('ix_rfqs_bom_line_id'), 'rfqs', ['bom_line_id'], unique=False)
    op.create_index(op.f('ix_rfqs_builder_org_id'), 'rfqs', ['builder_org_id'], unique=False)
    op.create_table('approvals',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('rfq_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_approvals_builder_org_id'), 'approvals', ['builder_org_id'], unique=False)
    op.create_index(op.f('ix_approvals_rfq_id'), 'approvals', ['rfq_id'], unique=False)
    op.create_table('negotiation_threads',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('public_code', sa.Text(), nullable=False),
    sa.Column('rfq_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('opening_offer_paise', sa.BigInteger(), nullable=True),
    sa.Column('current_offer_paise', sa.BigInteger(), nullable=True),
    sa.Column('last_counter_paise', sa.BigInteger(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nudged', sa.Boolean(), nullable=False),
    sa.Column('unclear_count', sa.Integer(), nullable=False),
    sa.Column('parse_fail_count', sa.Integer(), nullable=False),
    sa.Column('disclosure_asks', sa.Integer(), nullable=False),
    sa.Column('handoff_reason', sa.Text(), nullable=True),
    sa.Column('handed_to_human_by', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['handed_to_human_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_code'),
    sa.UniqueConstraint('rfq_id', 'vendor_id')
    )
    op.create_index(op.f('ix_negotiation_threads_builder_org_id'), 'negotiation_threads', ['builder_org_id'], unique=False)
    op.create_index(op.f('ix_negotiation_threads_rfq_id'), 'negotiation_threads', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_negotiation_threads_vendor_id'), 'negotiation_threads', ['vendor_id'], unique=False)
    op.create_table('quotes',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('public_code', sa.Text(), nullable=False),
    sa.Column('rfq_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('raw_file_ref', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('unit_price_paise', sa.BigInteger(), nullable=True),
    sa.Column('price_unit', sa.Text(), nullable=True),
    sa.Column('gst_included', sa.Boolean(), nullable=False),
    sa.Column('gst_bp', sa.Integer(), nullable=True),
    sa.Column('freight_paise', sa.BigInteger(), nullable=False),
    sa.Column('freight_included', sa.Boolean(), nullable=False),
    sa.Column('unloading_paise', sa.BigInteger(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('validity_until', sa.Date(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('qty_offered_milli', sa.BigInteger(), nullable=True),
    sa.Column('stated_total_paise', sa.BigInteger(), nullable=True),
    sa.Column('parse_confidence', sa.Integer(), nullable=True),
    sa.Column('confirmed_by_vendor_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_code'),
    sa.UniqueConstraint('rfq_id', 'vendor_id', 'revision')
    )
    op.create_index(op.f('ix_quotes_builder_org_id'), 'quotes', ['builder_org_id'], unique=False)
    op.create_index(op.f('ix_quotes_rfq_id'), 'quotes', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_quotes_vendor_id'), 'quotes', ['vendor_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('rfq_id', sa.Uuid(), nullable=False),
    sa.Column('ranked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('l1_vendor_id', sa.Uuid(), nullable=True),
    sa.Column('lowest_price_vendor_id', sa.Uuid(), nullable=True),
    sa.Column('split_proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['l1_vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['lowest_price_vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_builder_org_id'), 'recommendations', ['builder_org_id'], unique=False)
    op.create_index(op.f('ix_recommendations_rfq_id'), 'recommendations', ['rfq_id'], unique=False)
    op.create_table('rfq_invitations',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('rfq_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfq_id', 'vendor_id')
    )
    op.create_index(op.f('ix_rfq_invitations_builder_org_id'), 'rfq_invitations', ['builder_org_id'], unique=False)
    op.create_index(op.f('ix_rfq_invitations_rfq_id'), 'rfq_invitations', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_rfq_invitations_vendor_id'), 'rfq_invitations', ['vendor_id'], unique=False)
    op.create_table('messages',
    sa.Column('builder_org_id', sa.Uuid(), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=True),
    sa.Column('invitation_id', sa.Uuid(), nullable=True),
    sa.Column('rfq_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('external_message_id', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template_name', sa.Text(), nullable=True),
    sa.Column('in_24h_window', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['invitation_id'], ['rfq_invitations.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['negotiation_threads.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_message_id')
    )
    op.create_index(op.f('ix_messages_builder_org_id'), 'messages', ['builder_org_id'], unique=False)
    op.create_index(op.f('ix_messages_rfq_id'), 'messages', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_messages_vendor_id'), 'messages', ['vendor_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('public_code', sa.Text(), nullable=False),
    sa.Column('rfq_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=True),
    sa.Column('qty_milli', sa.BigInteger(), nullable=False),
    sa.Column('unit_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('subtotal_paise', sa.BigInteger(), nullable=False),
    sa.Column('gst_paise', sa.BigInteger(), nullable=False),
    sa.Column('freight_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('partial_allowed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('confirm_by', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_ref', sa.Text(), nullable=True),
    sa.Column('shortfall_note', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_code')
    )
    op.create_index(op.f('ix_work_orders_builder_org_id'), 'work_orders', ['builder_org_id'], unique=False)
    op.create_index(op.f('ix_work_orders_rfq_id'), 'work_orders', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_work_orders_vendor_id'), 'work_orders', ['vendor_id'], unique=False)
    op.create_table('capacity_reservations',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_item_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('qty_reserved_milli', sa.BigInteger(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_id')
    )
    op.create_index('ix_capacity_vendor_item_week', 'capacity_reservations', ['vendor_id', 'catalog_item_id', 'week_start'], unique=False)
    op.create_table('deliveries',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('public_code', sa.Text(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vehicle_no', sa.Text(), nullable=True),
    sa.Column('dispatched_qty_milli', sa.BigInteger(), nullable=True),
    sa.Column('received_qty_milli', sa.BigInteger(), nullable=True),
    sa.Column('received_photo_ref', sa.Text(), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_code'),
    sa.UniqueConstraint('work_order_id', 'seq')
    )
    op.create_index(op.f('ix_deliveries_builder_org_id'), 'deliveries', ['builder_org_id'], unique=False)
    op.create_index(op.f('ix_deliveries_work_order_id'), 'deliveries', ['work_order_id'], unique=False)
    op.create_table('invoices',
    sa.Column('builder_org_id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('file_ref', sa.Text(), nullable=True),
    sa.Column('invoice_no', sa.Text(), nullable=True),
    sa.Column('po_code_stated', sa.Text(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('unit_price_paise', sa.BigInteger(), nullable=True),
    sa.Column('mismatch_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['builder_org_id'], ['builder_orgs.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_builder_org_id'), 'invoices', ['builder_org_id'], unique=False)
    op.create_index(op.f('ix_invoices_work_order_id'), 'invoices', ['work_order_id'], unique=False)
    op.create_table('price_history',
    sa.Column('catalog_item_id', sa.Uuid(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('unit_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('landed_paise', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_items.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_order_id')
    )
    op.create_index('ix_price_history_item_region_date', 'price_history', ['catalog_item_id', 'region', 'date'], unique=False)
    # ### end Alembic commands ###
    op.execute(AUDIT_GUARD)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER audit_log_no_update_delete ON audit_log")
    op.execute("DROP FUNCTION audit_log_immutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_history_item_region_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_invoices_work_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_builder_org_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_deliveries_work_order_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_builder_org_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index('ix_capacity_vendor_item_week', table_name='capacity_reservations')
    op.drop_table('capacity_reservations')
    op.drop_index(op.f('ix_work_orders_vendor_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_rfq_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_builder_org_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_messages_vendor_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_rfq_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_builder_org_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_rfq_invitations_vendor_id'), table_name='rfq_invitations')
    op.drop_index(op.f('ix_rfq_invitations_rfq_id'), table_name='rfq_invitations')
    op.drop_index(op.f('ix_rfq_invitations_builder_org_id'), table_name='rfq_invitations')
    op.drop_table('rfq_invitations')
    op.drop_index(op.f('ix_recommendations_rfq_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_builder_org_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_quotes_vendor_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_rfq_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_builder_org_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_negotiation_threads_vendor_id'), table_name='negotiation_threads')
    op.drop_index(op.f('ix_negotiation_threads_rfq_id'), table_name='negotiation_threads')
    op.drop_index(op.f('ix_negotiation_threads_builder_org_id'), table_name='negotiation_threads')
    op.drop_table('negotiation_threads')
    op.drop_index(op.f('ix_approvals_rfq_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_builder_org_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_rfqs_builder_org_id'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_bom_line_id'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_bom_lines_builder_org_id'), table_name='bom_lines')
    op.drop_index(op.f('ix_bom_lines_bom_id'), table_name='bom_lines')
    op.drop_table('bom_lines')
    op.drop_index(op.f('ix_boms_builder_org_id'), table_name='boms')
    op.drop_table('boms')
    op.drop_index(op.f('ix_users_builder_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('unit_conversions')
    op.drop_index(op.f('ix_sites_builder_org_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_builder_vendor_links_vendor_id'), table_name='builder_vendor_links')
    op.drop_index(op.f('ix_builder_vendor_links_builder_org_id'), table_name='builder_vendor_links')
    op.drop_table('builder_vendor_links')
    op.drop_index(op.f('ix_audit_log_builder_org_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index('ix_jobs_status_run_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('demo_clock')
    op.drop_index('ix_catalog_items_name_trgm', table_name='catalog_items', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_catalog_items_category'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_table('builder_orgs')
    # ### end Alembic commands ###
    for seq in SEQUENCES:
        op.execute(f"DROP SEQUENCE {seq}")
