"""demo settings

Revision ID: f8d2000c34fa
Revises: 84fd18c451f6
Create Date: 2026-09-28 03:20:21.431568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8d2000c34fa'
down_revision: Union[str, Sequence[str], None] = '84fd18c451f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_clock', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo_clock', 'settings')
    # ### end Alembic commands ###
